# Building Docker Image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/propeller:$SHORT_SHA', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/propeller:${_IMAGE_TAG}', '.' ]

# Pushing Docker Image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    docker push europe-west1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/propeller:$SHORT_SHA
    docker push europe-west1-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/propeller:${_IMAGE_TAG}


  #
  # options:
  #   logging: CLOUD_LOGGING_ONLY
