---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propeller-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: propeller-test
          image: #gcr link to image goes here
          ports:
           —containerPort: 3000
